### ISSUE TITLE
iOS could use UIImpactFeedbackGenerator

### ISSUE THREAD

**Issue by MikePaer** [jamesmontemagno/VibratePlugin#3]
## Feature Request:
It would be awesome to have an option to use the iOS advanced haptic feedback instead of the standard long vibrate command on iOS. Something like:

```
var impact = new UIImpactFeedbackGenerator(UIImpactFeedbackStyle.Heavy);
impact.Prepare();
impact.ImpactOccurred();
```

**Comment by jamesmontemagno** [comment]
Cool! Let me take a look.

**Comment by jamesmontemagno** [comment]
I tested it on a device and it doesn't seem to do anything... I have an iPhone 6... Maybe it is only on the iPhone 6s and 7s?

**Comment by jamesmontemagno** [comment]
Looking at this thread it looks no good for now :( 

https://twitter.com/TimOliverAU/status/778105029643436033

Basically you have to use private selectors to see if the device supports it and there is no way of knowing if it actually works.

**Comment by MikePaer** [comment]
It must be a 6s or 7 feature. I have a 7, and it works on my device. In my code, hackily check for iPhone7+ using this https://github.com/dannycabrera/Get-iOS-Model and call `UIImpactFeedbackGenerator` if 7+. Otherwise, I call the usual `AudioToolbox.SystemSound.Vibrate.PlaySystemSound()`

**Comment by jamesmontemagno** [comment]
It is a good workaround for personal apps, but wouldn't feel comfortable putting it in the library. perhaps Apple will fix their API to check if haptics is there... silly it doesn't expose it.
