### ISSUE TITLE
cannot convert from 'int' to 'System.TimeSpan

### ISSUE THREAD

**Issue by mwallon** [jamesmontemagno/VibratePlugin#4]
Hi when I try to run this in my appliction by simply adding this line of code: CrossVibrate.Current.Vibration(500);

I get this error:
Error CS1503: Argument 1: cannot convert from 'int' to 'System.TimeSpan?' (CS1503) 

Do you know what that might be?

Best Regards
/magnus

**Comment by jamesmontemagno** [comment]
It is n ow a timespan, change your code

**Comment by jamesmontemagno** [comment]
Update docs

**Comment by smaritem** [comment]
Hey, 
maybe this one can help
TimeSpan.FromSeconds(10), 50 );
OR
FromMinutes
...
