### ISSUE TITLE
iOS vibrate only works when "Vibrate on ring" is turned on

### ISSUE THREAD

**Issue by nickginis** [jamesmontemagno/VibratePlugin#8]
## Bug Information

Version Number of Plugin: 4.0.0.5
Device Tested On: iPhone 7
Simulator Tested On: N/A
Version of VS: 2017
Version of Xamarin: 3.1
Versions of other things you are using: iOS 11.3.1

### Steps to reproduce the Behavior

On the iPhone have "Vibrate on silent" turned on and phone set to silent. 

The vibrate that should occur via the app DOES NOT occur.

On the iPhone have "Vibrate on ring" turned on.

The vibrate that should occur via the app DOES occur.

### Expected Behavior

The vibrate should occur whenever vibrate is allowed by the device

### Actual Behavior

The vibrate is only occurring when "Vibrate on ring" is turned on

### Code snippet

var v = CrossVibrate.Current;
v.Vibration(TimeSpan.FromSeconds(1.5)); 

### Screenshot:

Location of setting on iOS:

![image](https://user-images.githubusercontent.com/38271674/42198705-11a6dec4-7ecd-11e8-95f5-14cb64e59926.png)

**Comment by jamesmontemagno** [comment]
Unfortunately this is how iOS handles it and there is no API to vibrate the device.
